name: Build LSA Whisperer
on:
  workflow_dispatch: # Allows you to manually run the workflow
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Prepare the build
      run: cmake .. -A x64 -DCMAKE_SYSTEM_VERSION=10.0.22621.0
      working-directory: builds
    - name: Run the build
      run: cmake --build .
      working-directory: builds
